### ISSUE TITLE
Filters with spaces are silently ignored

### ISSUE THREAD

**Issue by GeorgeHahn** [dewey/miniflux-sidekick#3]
Filters with more than 2 spaces are silently ignored. It would be great if these worked (or failed loudly).

Two example filters:

```
ignore-article "*" "title =~ Update for .*day"
ignore-article "*" "title # Daily Deals"
```

**Comment by dewey** [comment]
Hey, I'll take a look. For some reason that repository wasn't "Watched" and I didn't get any notifications, sorry about the delay!
