### ISSUE TITLE
Make title tag matching case insensitive.

### ISSUE THREAD

**Issue by dsully** [dewey/miniflux-sidekick#8]
I have a killfile where I need to do this:

`ignore-article "https://electrek.co/feed/" "title # Podcast,podcast,Motorcyle,motorcyle,Scooter,scooter,Moped,moped"`

Which is a bit obnoxious. It'd be nice if the matching could be case insensitive.

**Comment by dewey** [comment]
I haven't tried it but have you tried achieving that by using the regular expression operator (`=~`)? Without testing it myself maybe the following could work:

~~`=~ (Podcast|Motorcyle|Scooter|Moped)/i`~~

I just [cleaned up the code a bit, added tests and tested your case](https://github.com/dewey/miniflux-sidekick/pull/9). The correct filter expression for your case would be the following. Note that the [case insensitive flag](https://golang.org/pkg/regexp/syntax/) has to be the first in the expression.

`title =~ (?i)(Podcast|scooter|your|Other|words)`

**Comment by dsully** [comment]
Not yet. I wasn't' sure if full regular expressions were available.

**Comment by dewey** [comment]
Our comments overlapped a bit here, let me know if it works. According to my tests now it should work with the syntax mentioned above. I also added it to the README now.
